universe                = docker
docker_image            = mosbachmarius/llmft:22.08-py3
executable              = $(PWD)/../experiments/pattern_verbalizer_ft/run.sh
output                  = ../outputs/run.sh.$(ClusterId).$(ProcId).$(Year)_$(Month)_$(Day)_$(SUBMIT_TIME).out
error                   = ../outputs/run.sh.$(ClusterId).$(ProcId).$(Year)_$(Month)_$(Day)_$(SUBMIT_TIME).err
log                     = ../outputs/run.sh.$(ClusterId).$(ProcId).$(Year)_$(Month)_$(Day)_$(SUBMIT_TIME).log
request_GPUs            = 8
request_CPUs            = 10
request_memory          = 100G
requirements            = (UidDomain == "cs.uni-saarland.de")
#&& (GPUs_GlobalMemoryMb >= 35000)
+WantGPUHomeMounted     = true
+PeriodicRemoveNotHold  = true
queue 1
